### PR TITLE
Update component screens

### PR DESCRIPTION
**Pull request by crstnmac**
<image src="https://user-images.githubusercontent.com/20360870/203232782-fb39e734-78b4-458d-a880-c23cd15c52f5.png" height="800" width="350" />

### CODE REVIEW

**Comment by crstnmac** [comment]
<p align="center">
<image src="https://user-images.githubusercontent.com/20360870/203316305-764a312d-3fa4-4dda-bea3-f536941b40ff.png" height="500" width="250"/>
&nbsp;&nbsp;&nbsp;&nbsp;
<image src="https://user-images.githubusercontent.com/20360870/203316501-9c869b38-c50f-4c07-ad87-5519f72a4bf7.png" height="500" width="250"/>
&nbsp;&nbsp;&nbsp;&nbsp;
<image src="https://user-images.githubusercontent.com/20360870/203317644-258040b9-ebfe-4570-9386-095f0b20d6d7.png" height="500" width="250"/>
</p>

**Comment by crstnmac** [comment]
<image src="https://user-images.githubusercontent.com/20360870/203490016-4fdb2207-d84b-46a3-915e-e8dfed25dd92.png" height=650 width=300/>

**Comment by crstnmac** [comment]
<image src=https://user-images.githubusercontent.com/20360870/203495532-0fb3cf69-152e-43d2-b793-0b2c1905602a.png height=600 width=270/>

**Comment by crstnmac** [comment]
<image src=https://user-images.githubusercontent.com/20360870/203519054-f44779e8-dbb5-4e16-ad87-4ee0d228f3de.png height=800 width=350 />

**Comment by crstnmac** [comment]
<image src=https://user-images.githubusercontent.com/20360870/203536659-d35df9b1-6ea5-4285-8c78-406b4e345c35.png height=800 width=350 />

**Comment by crstnmac** [comment]
<image src=https://user-images.githubusercontent.com/20360870/203550156-0be0858d-4081-45b0-a23e-716b3927fc5f.png height=800 width=350 />

**Comment by Karthik-B-06** [comment]
@crstnmac The determinate-indeterminate can be Switch? Or you can change the button text to `Reset` for determinate and `Make Indeterminate` for indeterminate. 

simulator_screenshot_80F48E94-8C73-4C80-8CB0-24D13C04430C

**Comment by crstnmac** [comment]
> @crstnmac The determinate-indeterminate can be Switch? Or you can change the button text to `Reset` for determinate and `Make Indeterminate` for indeterminate. 
> 
> simulator_screenshot_80F48E94-8C73-4C80-8CB0-24D13C04430C
> 

Okay 👍

**Comment by Karthik-B-06** [comment]
Hey @crstnmac can we please use the <Slot /> icon everywhere there is a need for prefixes and suffixes?

**Comment by Karthik-B-06** [comment]
Can you also resolve the conflicts, please. @crstnmac

**Comment by Karthik-B-06** [comment]
@crstnmac There is no Prefix prop controllable in InputScreen.
Screenshot 2022-12-02 at 10 57 42 AM

**Comment by Karthik-B-06** [comment]
@crstnmac Can you please fix the disabled switch alignment here?
Screenshot 2022-12-02 at 11 50 06 AM

**Comment by Karthik-B-06** [comment]
@crstnmac Why does the button text always read Tooltip on Top?

Screenshot 2022-12-02 at 11 51 34 AM

**Comment by crstnmac** [comment]
> @crstnmac Can you please fix the disabled switch alignment here? I think its the Switch Screen. Screenshot 2022-12-02 at 11 50 06 AM

done

**Comment by Karthik-B-06** [comment]
@crstnmac There is no Suffix prop control in Text Area Screen, can you please add them too?

**Comment by crstnmac** [comment]
> @crstnmac There is no Suffix prop control in Text Area Screen, can you please add them too?

ok

**Review by Karthik-B-06 — APPROVED** [review]
LGTM 🎉

**Pull request merged**
